### ISSUE TITLE
Doesn't work on Update 9 :(

### ISSUE THREAD

**Issue by Vistaus** [prplmnky/harbour-duckduckgo#1]
I change it to DDG using this app but the browser doesn't pick it up :(

**Comment by dpeytonX** [comment]
Yeah, I also noticed they added the Yandex search (which may or may not be related). I'll see if I can rewrite this app so that it passes Harbour Store's stringent requirements (and Update 9).

**Comment by dpeytonX** [comment]
They changed a lot with update 9
- /usr/share/jolla-settings/pages/browser.qml - Uses a BrowserSettings (which appears to be a QML C++ plugin) to get the valid search engines
- The BrowserSettings has a read only property called "searchEngineList" which maintains the Checkbox values for the search page. This used to be a hard coded list in QML
- The settings key "/apps/sailfish-browser/settings/search_engine" is settable, but there's probably error checking in the Browser application which defaults to Bing if the search engine isn't in BrowserSettings

Not sure I can fix this without tracking down the source code and making an involved hack which will probably not work with Update 10.

Closing this issue for now and will wait to see what happens.

P.S> I created a bookmark for DuckDuckGo in the browser now. It sucks that Jolla has made it so hard to extend such a miniscule setting, but "it is what it is".

**Comment by dpeytonX** [comment]
I will try to implement the workaround by editing an existing search plugin so that Browser won't erase it.

**Comment by dpeytonX** [comment]
Browser is not checking permissions. It is actually checking the search name field. As long as this remains intact, the file will not be updated!

**Comment by dpeytonX** [comment]
This should be fixed in 2.0
